### ISSUE TITLE
issue with sizefactors when using sparse matrices

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/batchglm#71] opened 2019-03-21 16:27 UTC
When running the unittest for graphs and checking wether size_factors is None here:
https://github.com/theislab/batchglm/blob/27b648e4130ed1689246e267741ffdafdd8f1520/batchglm/train/tf/base_glm_all/estimator.py#L143
it seems to be None, when setting sparse=False, but not to be None, when sparse=True.

**Comment by SabrinaRichter** [comment] 2019-03-27 12:42
Also here:
https://github.com/theislab/batchglm/blob/612fb63789d803528d5b5898992f114b5221c1c8/batchglm/models/base_glm/utils.py#L133
sizefactors are None when X is not sparse and not None when X is sparse.
I just can't figure out where sizefactors are set to something not None, when X is sparse.

**Comment by picciama** [comment] 2022-03-04 12:33
@SabrinaRichter is this still relevant? The issue is nearly 3 years old. We have decided to retire support for tf1 entirely. I haven't seen this behaviour in tf2 backend nor in numpy backend. Both will be using an entirely restructured input data processing pipeline and this seems to be a problem specific to the input data processing in tf1 backend. I close this for now.

**Closed by picciama** 2022-03-04 12:33 UTC
Labels: wontfix
